{% set name = "svtoolbox" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=77
    - wheel
  run:
    - python >=3.10
    - click
    - pysam

test:
  imports:
    - svtoolbox
  commands:
    - svtoolbox --help
    - svtoolbox create-bedpe --help
    - svtoolbox create-contigs-fastq --help

about:
  home: https://github.com/MOMA-AUH/svtoolbox
  summary: Command-line tools for converting structural variant calls and extracting assembled contigs
  license: MIT
  license_file: LICENSE
